# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expansions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expansion',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
