# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_card_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='faction',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='flavour',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='mechanics',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
    ]
